<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2024-10-30 19:04:29 --> Query error: Unknown column 'user_id' in 'field list' - Invalid query: INSERT INTO `tracking` (`user_id`, `trackee_id`, `tracking_type`, `mode_backend`, `share_time`, `tracker_id`, `start_time`) VALUES ('5256', '5256', '2', '1', '30', 0, '2024-10-30 19:04:29')
ERROR - 2024-10-30 19:05:00 --> Query error: Unknown column 'user_id' in 'field list' - Invalid query: INSERT INTO `tracking` (`user_id`, `trackee_id`, `tracking_type`, `mode_backend`, `share_time`, `tracker_id`, `start_time`) VALUES ('5256', '5256', '2', '1', '30', 0, '2024-10-30 19:05:00')
ERROR - 2024-10-30 19:06:49 --> Query error: Unknown column 'user_id' in 'field list' - Invalid query: INSERT INTO `tracking` (`user_id`, `trackee_id`, `tracking_type`, `mode_backend`, `share_time`, `mode`, `tracker_id`, `start_time`) VALUES ('5256', '5256', '2', '1', '30', '1', 0, '2024-10-30 19:06:49')
ERROR - 2024-10-30 19:19:19 --> Query error: Unknown column 'user_id' in 'field list' - Invalid query: INSERT INTO `tracking` (`user_id`, `trackee_id`, `tracking_type`, `mode_backend`, `share_time`, `mode`, `tracker_id`, `start_time`) VALUES ('5256', '5256', '2', '1', '30', '1', 0, '2024-10-30 19:19:19')
ERROR - 2024-10-30 19:30:10 --> Query error: Unknown column 'user_id' in 'field list' - Invalid query: INSERT INTO `tracking` (`user_id`, `trackee_id`, `tracking_type`, `mode_backend`, `share_time`, `start_location`, `mode`, `tracker_id`, `start_time`) VALUES ('5256', '5256', '2', '1', '30', '{\"lat\":21.208292,\"lng\":81.4011505,\"power\":\"\",\"time\":1730277010150,\"date_value\":\"2024-10-30 14:00:10.150\"}', '1', 0, '2024-10-30 19:30:10')
ERROR - 2024-10-30 19:31:30 --> Query error: Unknown column 'user_id' in 'field list' - Invalid query: INSERT INTO `tracking` (`user_id`, `trackee_id`, `tracking_type`, `mode_backend`, `share_time`, `mode`, `tracker_id`, `start_time`) VALUES ('5256', '5256', '2', '1', '30', '1', 0, '2024-10-30 19:31:30')
ERROR - 2024-10-30 19:34:31 --> Query error: Unknown column 'user_id' in 'field list' - Invalid query: INSERT INTO `tracking` (`user_id`, `trackee_id`, `tracking_type`, `mode_backend`, `share_time`, `mode`, `tracker_id`, `start_time`) VALUES ('5256', '5256', '2', '1', '30', '1', 0, '2024-10-30 19:34:31')
ERROR - 2024-10-30 19:42:32 --> Query error: Unknown column 'user_id' in 'field list' - Invalid query: INSERT INTO `tracking` (`user_id`, `trackee_id`, `tracking_type`, `mode_backend`, `share_time`, `mode`, `start_location`, `tracker_id`, `start_time`) VALUES ('5256', '5251', '1', '1', '30', '1', '{\"lat\":\"81.5647636743\",\"lng\":\"91.654434734\",\"power\":\"\",\"time\":\"324325564\",\"date_value\":\"2024-10-30 18:51:30\"}', '6171', '2024-10-30 19:42:32')
